apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
spec:
  limits:
  - default:
      cpu: {{.Values.limitrange.request.cpu}}m
      memory: {{.Values.limitrange.request.memory}}Mi
    defaultRequest:
      cpu: {{.Values.limitrange.request.cpu}}m
      memory: {{.Values.limitrange.request.memory}}Mi
    max:
      cpu: {{.Values.limitrange.limit.cpu}}m
      memory: {{.Values.limitrange.limit.memory}}Mi
    min:
      cpu: {{.Values.limitrange.request.cpu}}m
      memory: {{.Values.limitrange.request.memory}}Mi
    type: Container
